#!/usr/bin/env bash

#SBATCH --partition=all
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=128G
#SBATCH --time=24:00:00
#SBATCH --job-name=checkm_pre_ref
#SBATCH --mail-type=END,FAIL

###############################################################################
# 13_pre_ref_check.sh
#
# Run CheckM on bins generated by MetaBAT2, CONCOCT, or MaxBin2 before
# bin refinement.
#
# Usage:
#   sbatch 13_pre_ref_check.sh \
#       GROUP BINNING_TOOL GLOBAL_BINNING_DIR MAXBIN_DIR
#
# Examples:
#   sbatch 13_pre_ref_check.sh all metabat \
#       data/binningRh/all_samples data/binningRh/maxbin
#
#   sbatch 13_pre_ref_check.sh all concoct \
#       data/binningRh/all_samples data/binningRh/maxbin
#
#   sbatch 13_pre_ref_check.sh CK maxbin \
#       data/binningRh/all_samples data/binningRh/maxbin
#
# Requirements:
#   CheckM 1.2.3
###############################################################################

set -euo pipefail


# ---------------------------------------------------------------------------
# Command-line arguments
# ---------------------------------------------------------------------------

if [[ $# -ne 4 ]]; then
    echo "Usage: sbatch $0 GROUP BINNING_TOOL GLOBAL_BINNING_DIR MAXBIN_DIR" >&2
    echo >&2
    echo "Valid combinations:" >&2
    echo "  all metabat" >&2
    echo "  all concoct" >&2
    echo "  CK  maxbin" >&2
    echo "  NP  maxbin" >&2
    echo "  NPM maxbin" >&2
    exit 1
fi

group="$1"
binning_tool="$2"
global_binning_dir="$3"
maxbin_dir="$4"

threads="${SLURM_CPUS_PER_TASK:-8}"


# ---------------------------------------------------------------------------
# Conda environment
# ---------------------------------------------------------------------------

conda_profile="${CONDA_PROFILE:-${HOME}/miniconda3/etc/profile.d/conda.sh}"
conda_environment="${CHECKM_CONDA_ENV:-base}"

if [[ ! -f "$conda_profile" ]]; then
    echo "ERROR: Conda initialization script not found: $conda_profile" >&2
    exit 1
fi

source "$conda_profile"
conda activate "$conda_environment"


# ---------------------------------------------------------------------------
# Validate requested group and binning tool
# ---------------------------------------------------------------------------

case "$binning_tool" in
    metabat|concoct)
        if [[ "$group" != "all" ]]; then
            echo "ERROR: GROUP must be 'all' for $binning_tool." >&2
            exit 1
        fi
        ;;

    maxbin)
        case "$group" in
            CK|NP|NPM)
                ;;
            *)
                echo "ERROR: GROUP must be CK, NP, or NPM for MaxBin2." >&2
                exit 1
                ;;
        esac
        ;;

    *)
        echo "ERROR: Invalid binning tool: $binning_tool" >&2
        echo "Allowed tools: metabat, concoct, maxbin" >&2
        exit 1
        ;;
esac


# ---------------------------------------------------------------------------
# Set tool-specific directories and filename patterns
# ---------------------------------------------------------------------------

case "$binning_tool" in
    metabat)
        bins_dir="${global_binning_dir}/metabat"
        bin_pattern="allRh_metabat_bin.*.fa"
        extension="fa"
        checkm_output_dir="${global_binning_dir}/metabat/checkm"
        ;;

    concoct)
        bins_dir="${global_binning_dir}/concoct/run/bins"
        bin_pattern="*.fa"
        extension="fa"
        checkm_output_dir="${global_binning_dir}/concoct/checkm"
        ;;

    maxbin)
        bins_dir="${maxbin_dir}/${group}"
        bin_pattern="${group}_maxbin.*.fasta"
        extension="fasta"
        checkm_output_dir="${maxbin_dir}/${group}/checkm"
        ;;
esac


# ---------------------------------------------------------------------------
# Validate inputs and software
# ---------------------------------------------------------------------------

if ! command -v checkm >/dev/null 2>&1; then
    echo "ERROR: checkm is not available in the active environment." >&2
    exit 1
fi

if [[ ! -d "$bins_dir" ]]; then
    echo "ERROR: Bin directory not found: $bins_dir" >&2
    exit 1
fi

bin_count=$(
    find "$bins_dir" \
        -maxdepth 1 \
        -type f \
        -name "$bin_pattern" \
        | wc -l
)

if [[ "$bin_count" -eq 0 ]]; then
    echo "ERROR: No bin files found." >&2
    echo "Bin directory: $bins_dir" >&2
    echo "Pattern:       $bin_pattern" >&2
    exit 1
fi

mkdir -p "$checkm_output_dir"


# ---------------------------------------------------------------------------
# Run CheckM
# ---------------------------------------------------------------------------

start_time=$(date +%s)

echo "[$(date)] Starting CheckM"
echo "Group:            $group"
echo "Binning tool:     $binning_tool"
echo "Bin directory:    $bins_dir"
echo "Bin pattern:      $bin_pattern"
echo "Number of bins:   $bin_count"
echo "Output directory: $checkm_output_dir"
echo "Threads:          $threads"
echo

checkm lineage_wf \
    --reduced_tree \
    -t "$threads" \
    -x "$extension" \
    "$bins_dir" \
    "$checkm_output_dir"


# ---------------------------------------------------------------------------
# Generate CheckM summary
# ---------------------------------------------------------------------------

summary_file="${checkm_output_dir}/checkm_summary.txt"

echo "[$(date)] Generating CheckM QA summary"

checkm qa \
    "${checkm_output_dir}/lineage.ms" \
    "$checkm_output_dir" \
    -o 2 \
    --tab_table \
    > "$summary_file"


# ---------------------------------------------------------------------------
# Filter bins by completeness and contamination
# ---------------------------------------------------------------------------

minimum_completeness=50
maximum_contamination=10
filtered_file="${checkm_output_dir}/high_quality_bins.txt"

awk -F '\t' \
    -v minimum_completeness="$minimum_completeness" \
    -v maximum_contamination="$maximum_contamination" \
    '
    NR > 1 &&
    $12 >= minimum_completeness &&
    $13 <= maximum_contamination {
        print $1 "\t" $12 "\t" $13
    }
    ' "$summary_file" \
    > "$filtered_file"


# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

end_time=$(date +%s)
runtime_minutes=$(( (end_time - start_time) / 60 ))
passing_bins=$(wc -l < "$filtered_file")

echo
echo "[$(date)] CheckM completed"
echo "Bins evaluated: $bin_count"
echo "Bins passing:   $passing_bins"
echo "Thresholds:     completeness >= ${minimum_completeness}%, contamination <= ${maximum_contamination}%"
echo "Summary:        $summary_file"
echo "Filtered bins:  $filtered_file"
echo "Runtime:        ${runtime_minutes} minutes"