#!/usr/bin/env bash

#SBATCH --partition=all
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=64G
#SBATCH --time=2-00:00:00
#SBATCH --job-name=das_allRh
#SBATCH --mail-type=END,FAIL

###############################################################################
# 14_dastool_refinement.sh
#
# Refine bins generated by MetaBAT2, MaxBin2, and CONCOCT using DAS Tool.
#
# Usage:
#   sbatch 14_dastool_refinement.sh \
#       ASSEMBLY METABAT_DIR MAXBIN_DIR CONCOCT_DIR OUTPUT_DIR
#
# Requirements:
#   DAS Tool
###############################################################################

set -euo pipefail


# ---------------------------------------------------------------------------
# Command-line arguments
# ---------------------------------------------------------------------------

if [[ $# -ne 5 ]]; then
    echo "Usage: sbatch $0 ASSEMBLY METABAT_DIR MAXBIN_DIR CONCOCT_DIR OUTPUT_DIR" >&2
    exit 1
fi

assembly="$1"
metabat_dir="$2"
maxbin_dir="$3"
concoct_dir="$4"
output_dir="$5"

threads="${SLURM_CPUS_PER_TASK:-8}"

concoct_bins_dir="${concoct_dir}/run/bins"
concoct_csv="${concoct_dir}/run/clustering_merged.csv"

output_base="${output_dir}/allRh"

metabat_tsv="${output_dir}/metabat_contigs2bin.tsv"
maxbin_tsv="${output_dir}/maxbin_contigs2bin.tsv"
concoct_tsv="${output_dir}/concoct_contigs2bin.tsv"


# ---------------------------------------------------------------------------
# Conda environment
# ---------------------------------------------------------------------------

conda_profile="${CONDA_PROFILE:-${HOME}/miniconda3/etc/profile.d/conda.sh}"

if [[ ! -f "$conda_profile" ]]; then
    echo "ERROR: Conda initialization script not found: $conda_profile" >&2
    exit 1
fi

source "$conda_profile"
conda activate binning-env


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

if [[ ! -s "$assembly" ]]; then
    echo "ERROR: Assembly file not found or empty: $assembly" >&2
    exit 1
fi

if [[ ! -d "$metabat_dir" ]]; then
    echo "ERROR: MetaBAT2 directory not found: $metabat_dir" >&2
    exit 1
fi

if [[ ! -d "$maxbin_dir" ]]; then
    echo "ERROR: MaxBin2 directory not found: $maxbin_dir" >&2
    exit 1
fi

if [[ ! -d "$concoct_dir" ]]; then
    echo "ERROR: CONCOCT directory not found: $concoct_dir" >&2
    exit 1
fi

if ! command -v DAS_Tool >/dev/null 2>&1; then
    echo "ERROR: DAS_Tool is not available in the active environment." >&2
    exit 1
fi

mkdir -p "$output_dir"


# ---------------------------------------------------------------------------
# Generate MetaBAT2 contig-to-bin table
# ---------------------------------------------------------------------------

: > "$metabat_tsv"

metabat_count=0

if compgen -G "${metabat_dir}/*.fa" >/dev/null; then
    for bin_file in "${metabat_dir}"/*.fa; do
        filename="$(basename "$bin_file" .fa)"

        case "$filename" in
            *lowDepth|*tooShort|*unbinned)
                continue
                ;;
        esac

        metabat_count=$((metabat_count + 1))
        bin_name="$(printf "metabat_%04d" "$metabat_count")"

        awk -v bin="$bin_name" '
            /^>/ {
                contig = $1
                sub(/^>/, "", contig)
                print contig "\t" bin
            }
        ' "$bin_file" >> "$metabat_tsv"
    done
else
    echo "WARNING: No MetaBAT2 bin files found in: $metabat_dir" >&2
fi


# ---------------------------------------------------------------------------
# Generate MaxBin2 contig-to-bin table
# ---------------------------------------------------------------------------

: > "$maxbin_tsv"

maxbin_count=0

for group in CK NP NPM; do
    group_dir="${maxbin_dir}/${group}"

    if [[ ! -d "$group_dir" ]]; then
        echo "WARNING: MaxBin2 directory not found for $group: $group_dir" >&2
        continue
    fi

    if compgen -G "${group_dir}/*.fasta" >/dev/null; then
        for bin_file in "${group_dir}"/*.fasta; do
            maxbin_count=$((maxbin_count + 1))
            bin_name="$(printf "maxbin_%04d" "$maxbin_count")"

            awk -v bin="$bin_name" '
                /^>/ {
                    contig = $1
                    sub(/^>/, "", contig)
                    print contig "\t" bin
                }
            ' "$bin_file" >> "$maxbin_tsv"
        done
    else
        echo "WARNING: No MaxBin2 bin files found in: $group_dir" >&2
    fi
done


# ---------------------------------------------------------------------------
# Generate CONCOCT contig-to-bin table
# ---------------------------------------------------------------------------

: > "$concoct_tsv"

concoct_count=0

if [[ -s "$concoct_csv" ]]; then
    tail -n +2 "$concoct_csv" |
        awk -F',' '
            NF >= 2 {
                print $1 "\t" "concoct_" $2
            }
        ' > "$concoct_tsv"

    concoct_count=$(
        awk -F '\t' '
            {
                bins[$2] = 1
            }
            END {
                print length(bins)
            }
        ' "$concoct_tsv"
    )

elif compgen -G "${concoct_bins_dir}/*.fa" >/dev/null; then
    for bin_file in "${concoct_bins_dir}"/*.fa; do
        concoct_count=$((concoct_count + 1))
        bin_name="$(printf "concoct_%04d" "$concoct_count")"

        awk -v bin="$bin_name" '
            /^>/ {
                contig = $1
                sub(/^>/, "", contig)
                print contig "\t" bin
            }
        ' "$bin_file" >> "$concoct_tsv"
    done
else
    echo "WARNING: No CONCOCT clustering file or bin files found." >&2
fi


# ---------------------------------------------------------------------------
# Select available binning sources
# ---------------------------------------------------------------------------

input_files=()
labels=()

if [[ -s "$metabat_tsv" ]]; then
    input_files+=("$metabat_tsv")
    labels+=("metabat")
fi

if [[ -s "$maxbin_tsv" ]]; then
    input_files+=("$maxbin_tsv")
    labels+=("maxbin")
fi

if [[ -s "$concoct_tsv" ]]; then
    input_files+=("$concoct_tsv")
    labels+=("concoct")
fi

if [[ ${#input_files[@]} -lt 2 ]]; then
    echo "ERROR: DAS Tool requires at least two binning sources." >&2
    echo "Detected sources: ${labels[*]:-none}" >&2
    exit 1
fi

input_string="$(IFS=,; echo "${input_files[*]}")"
label_string="$(IFS=,; echo "${labels[*]}")"


# ---------------------------------------------------------------------------
# Run DAS Tool
# ---------------------------------------------------------------------------

start_time=$(date +%s)

echo "[$(date)] Starting DAS Tool refinement"
echo "Assembly:          $assembly"
echo "MetaBAT2 bins:     $metabat_count"
echo "MaxBin2 bins:      $maxbin_count"
echo "CONCOCT bins:      $concoct_count"
echo "Detected sources:  $label_string"
echo "Input tables:      $input_string"
echo "Output prefix:     $output_base"
echo "Threads:           $threads"
echo

DAS_Tool \
    -i "$input_string" \
    -l "$label_string" \
    -c "$assembly" \
    -o "$output_base" \
    -t "$threads" \
    --write_bins \
    --debug


# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

end_time=$(date +%s)
runtime_minutes=$(( (end_time - start_time) / 60 ))

summary_file="${output_base}.DAS_Tool.summary.tsv"
refined_bins_dir="${output_base}_DASTool_bins"

echo
echo "[$(date)] DAS Tool refinement completed"
echo "Summary: $summary_file"
echo "Bins:    $refined_bins_dir"
echo "Runtime: ${runtime_minutes} minutes"